# Application
app.name=sihati
app.domain=http://sihati.loc.elit.dz
app.cordinateur.url=https://10.6.98.79:9191/Coordinateur/api/production
app.cordinateur.user=tuqqna.tbt
app.cordinateur.password=
app.cordinateur.instance=TDB
springdoc.swagger-ui.path=/swagger-ui-custom.html
# Server
#server.port=80
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
server.tomcat.basedir=../../repot
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.pattern="%t %a %{x-forwarded-for}i %{user}r  request:%{SESSIONID}r %m %U %s %q %r  "
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.address=0.0.0.0
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
# Enable HTTP/2 support, if the current environment supports it
server.http2.enabled=true

# Maximum time the response should be cached (in seconds)
spring.resources.cache.cachecontrol.max-age=120
# The cache must re-validate with the server.
# Any expired resources must not be used without re-validating.
spring.resources.cache.cachecontrol.must-revalidate=true
# Cache period for the resources served by the resource handler (in seconds)
spring.resources.cache.period=3600

# enable multipart file uploads
spring.servlet.multipart.enabled=true
# Write files to disk if the file size is more than 2KB.
spring.servlet.multipart.file-size-threshold=2KB
# Maximum file size that can be uploaded
spring.servlet.multipart.max-file-size=50MB
# Maximum allowed multipart request size
spring.servlet.multipart.max-request-size=75MB

file.upload-dir=./uploads
file.print-dir=./print

# security
app.security.default-password=Elit.2017
app-security.auth_header=Authorization
app-security.expires_in_seconds=14400
app-security.max_attempt=5
app-security.bocked_in_second=60
app-security.refreshed_time_lapse_seconds=3000
app-security.secret=Amine24h
app-security.ip_domain=localhost
app-security.port_domain=4200
app-security.path_key_public=../key/public_key.pem
app-security.path_key_private=../key/private_key.pem
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sihati?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.flyway.schemas=admin

## Jasypt
#jasypt.encryptor.password=${SECRET_ENCRYPTION_KEY}
#jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
#jasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256

spring.flyway.baseline-on-migrate=true

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Hibernate ddl auto (validate, update, create, create-drop, none)
spring.jpa.hibernate.ddl-auto=update
script.command=script.sql
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Config for logger (Verbose, Debug, Information, Warning, Error, Fatal)
app.logger.seq.url=http://localhost:5341/
app.logger.rollingfile.pathtemplate=logs/log-{Date}.log
app.logger.level=Debug

logging.level.org.springframework.web=debug
logging.level.org.hibernate=error
logging.level.org.apache.tomcat=debug
logging.level.org.apache.catalina=debug
notification.service.url=https://192.168.1.2:8443
# Cache properties
spring.cache.redis.cache-null-values=false
spring.redis.lettuce.pool.max-active=7
spring.redis.lettuce.pool.max-idle=7
spring.redis.lettuce.pool.min-idle=2
spring.redis.lettuce.pool.max-wait=-1ms
spring.redis.lettuce.shutdown-timeout=200ms

app.cache.timeoutSeconds=60
app.cache.redisHost=localhost
app.cache.redisPort=6379
app.cache.timeout=60
app.cache.cacheExpirations.top-notifications=180

spring.boot.admin.client.url=http://localhost:8080

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans
management.endpoint.shutdown.enabled=true
management.endpoint.health.show-details=always

jasper.url=http://10.100.1.42:8082/jasperserver/rest_v2/reports/reports/sihati
jasper.username=aka
jasper.password=a

spring.data.web.pageable.size-parameter=limit
spring.data.web.pageable.page-parameter=offset

#MAIL
spring.mail.username=sihati.sonelgaz-test
spring.mail.password=GVdqb.5514
spring.mail.host=10.6.1.28
spring.mail.port=465
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.starttls.required = true
spring.mail.properties.mail.smtp.ssl.enable = true
spring.mail.properties.mail.smtp.host = 10.6.1.28
spring.mail.properties.mail.smtp.port = 465
spring.mail.properties.mail.ssl.trust = *
app.mail.properties.from=sihati.sonelgaz-test@sonelgaz-serv.dz
#QUARTZ
using.spring.schedulerFactory=true
spring.quartz.job-store-type=memory

#SSL CERTIFICATE
server.port: 8443
server.ssl.key-store:keystore
server.ssl.key-store-password:Elit.2017
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat

base.url=http://localhost:4200
redis.token.prefix=CHANGE_PASSWORD:
redis.token.prefix.ip=TRUSTED_IP:

output-path = "${user.dir}\\pdf-output\\"
jasperreports.pdf.report.size-page-to-content=true
jasperreports.pdf.report.force-line-break-policy= false
jasperreports.pdf.export.metadata-author= TDB
jasperreports.pdf.export.report-encrypted= true
jasperreports.pdf.export.allowed-permissions-hint=PRINTING
jasperreports.pdf.export.report-compressed= true

validation.locales =  "Er" , "Ar"