
org.quartz.scheduler.instanceName = JobScheduler
org.quartz.scheduler.instanceId = AUTO

org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 1

#org.quartz.jobStore.dataSource=
org.quartz.jobStore.class=org.springframework.scheduling.quartz.LocalDataSourceJobStore
#org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.tablePrefix=quartz.qrtz_
org.quartz.jobStore.misfireThreshold = 600000
org.quartz.datasource.quartzDataSource.driver= org.postgresql.Driver